api_platform:
  title: "BMA: Budget Manager API"
  description: "An API to create and manage your budget adding or subtract transactions."
  version: 0.0.1

  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
    api_keys:
      apiKey:
        name: Authorization
        type: header
