#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /get_token
  methods: ['POST']

api_refresh_token:
  path: /refresh_token
  methods: [ 'POST' ]