@startuml
!theme materia
skinparam actorStyle awesome
skinparam roundcorner 10
skinparam BackgroundColor #555555
skinparam usecase{
    BackgroundColor white
    FontColor black
}
skinparam Actor{
    BackgroundColor white
    BorderColor black
    FontColor white
    FontStyle bold
}
skinparam rectangle{
    BackgroundColor WhiteSmoke
}
left to right direction
'----------------------------------------------

actor :User: as U
actor :API ADMIN: as ADM
actor :BUDGET MANAGER: as BM

ADM -> (manage resource user CRUD)

U -> ([v] can authenticate)
U -> (can reset password)



rectangle BUDGET{
    BM --> (can see a list of his budgets)
    BM --> (create Budget)
    BM --> (can see current budgets balances)
    BM --> (can see the expected budgets balances)
    BM --> (can delete Budget)
    BM --> (can see a list of operations relative to Budget)
}
rectangle TRANSACTION{
 BM --> (create Transaction)
 BM --> (can add expenses to the budget)
 BM --> (can add money to the budget )
 BM --> (can create recurring operation list)
 BM --> (can add Transaction to Recurring operations List)
}


@enduml
