@startuml
!theme materia
skinparam actorStyle awesome
skinparam roundcorner 10
skinparam BackgroundColor #555555
skinparam usecase{
    BackgroundColor white
    FontColor black
}
skinparam Actor{
    BackgroundColor white
    BorderColor black
    FontColor white
    FontStyle bold
}
skinparam rectangle{
    BackgroundColor WhiteSmoke
}
left to right direction
'----------------------------------------------

actor :ADMIN: as ADM
actor :User: as U

ADM -> (manage resource "User" CRUD)

rectangle USER{
    U -> ([v] can authenticate)
    U -> ([v] can update password)
}

rectangle BUDGET{
    U --> ([v] create Budget)
    U --> (can see a list of his budgets)
    U --> (can see current budgets balances)
    U --> (can see the expected budgets balances)
    U --> (can delete Budget)
    U --> (can see a list of operations relative to Budget)
}
rectangle TRANSACTION{
 U --> ([v] can add expenses to the budget)
 U --> ([v] can add money to the budget)
}


@enduml
