@startuml
'https://plantuml.com/class-diagram
!theme cerulean-outline
skinparam backgroundColor white
'----------------------------------------------

class User{
        -id
        -email
        -password
        -roles
}

class Budget {

    - id: int
    - name: string
    - startAmount: int
    - startAt: DateTime
    - endAt: DateTime
    - budgetTransaction: BudgetTransaction[]

    + __construct(string budgetName)
    + getBalanceAt(DateTime date)

}

class Transaction {

    - id: int
    - amount: int
}

class BudgetTransaction {

    - id: int
    - createdAt: DateTime
    - isNegative: ?bool
    - isRecurrent: ?bool
    - transactionId: int (FK)
    - budgetId: int (FK)
}

@enduml